/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rms.screens;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import rms.models.MenuItem;
import rms.models.Order;
import rms.resources.MenuDbHandler;
import rms.resources.OrdersDbHandler;
import rms.resources.utils;

/**
 *
 * @author rammy
 */
public class app_Screen extends javax.swing.JFrame {
    private DefaultTableModel tableModel1,tableModel2;
    private DefaultListModel listModel1,listModel2;
    private MenuDbHandler menuDb;
    private OrdersDbHandler ordersDb;
    private ArrayList<MenuItem> currentOrderItems;
    private ArrayList<Order> orders;
    /**
     * Creates new form app_Screen
     */
    public app_Screen() {
        initComponents();
        Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
        setTitle("Rate-a-Touille");
        setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        setResizable(false);
        
        currentOrderItems=new ArrayList();
        menuDb=new MenuDbHandler();
        ordersDb=new OrdersDbHandler();
        
        tableModel1=new DefaultTableModel();
        listModel1=new DefaultListModel();
        orderItemsList.setModel(listModel1);
        
        tableModel1.addColumn("NAME");
        tableModel1.addColumn("PRICE");
        
        menuTable.setModel(tableModel1);
        
        ArrayList<MenuItem> items=menuDb.getMenu();
        
        for(MenuItem item:items){
            tableModel1.addRow(new String[]{item.getName(),String.valueOf(item.getPrice())});
        }
        
        initOrdersListModel();
        initDetailsTableModel();
    }
    
    private void initOrdersListModel(){
        listModel2=new DefaultListModel();
        orders=utils.arrangeOrders(ordersDb.getOrders());
        for(Order order:orders){
            listModel2.addElement("Order: "+order.getId());
        }
        ordersList.setModel(listModel2);
    }
    
    private void initDetailsTableModel(){
        tableModel2=new DefaultTableModel();
        detailsTable.setModel(tableModel2);
        tableModel2.addColumn("NAME");
        tableModel2.addColumn("PRICE");
        tableModel2.addColumn("QUANTITY");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderItemsList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ordersList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        placeOrderBtn = new javax.swing.JButton();
        remMenuBtn = new javax.swing.JButton();
        addMenuBtn = new javax.swing.JButton();
        MenuQtyTxt = new javax.swing.JTextField();
        orderRefreshBtn = new javax.swing.JButton();
        remOrderBtn = new javax.swing.JButton();
        showDetailsBtn = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        appendOrderBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rate-a-Touille");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Orders");

        jScrollPane1.setViewportView(menuTable);

        jScrollPane2.setViewportView(orderItemsList);

        jScrollPane3.setViewportView(ordersList);

        jScrollPane4.setViewportView(detailsTable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Qty:");

        placeOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        placeOrderBtn.setText("Place Order");
        placeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBtnActionPerformed(evt);
            }
        });

        remMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remMenuBtn.setText("Remove");
        remMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remMenuBtnActionPerformed(evt);
            }
        });

        addMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addMenuBtn.setText("Add");
        addMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuBtnActionPerformed(evt);
            }
        });

        MenuQtyTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        orderRefreshBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderRefreshBtn.setText("Refresh");
        orderRefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderRefreshBtnActionPerformed(evt);
            }
        });

        remOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remOrderBtn.setText("Remove");
        remOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remOrderBtnActionPerformed(evt);
            }
        });

        showDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showDetailsBtn.setText("Show Details");
        showDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsBtnActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        totalLabel.setText("Total:");

        appendOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        appendOrderBtn.setText("Append Order");
        appendOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appendOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MenuQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(addMenuBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remMenuBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placeOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appendOrderBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showDetailsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remOrderBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderRefreshBtn))
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placeOrderBtn)
                    .addComponent(remMenuBtn)
                    .addComponent(addMenuBtn)
                    .addComponent(MenuQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderRefreshBtn)
                    .addComponent(remOrderBtn)
                    .addComponent(showDetailsBtn)
                    .addComponent(totalLabel)
                    .addComponent(appendOrderBtn))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBtnActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        String date = df.format(new Date());
        String orderItems="";
        for (MenuItem item:currentOrderItems){
            orderItems+=item.getId()+":"+item.getQty()+",";
        }
        orderItems=orderItems.substring(0,orderItems.length()-1);
        ordersDb.addOrder2(date,orderItems);
        listModel1.clear();
        MenuQtyTxt.setText("");
        currentOrderItems.clear();
        initOrdersListModel();
    }//GEN-LAST:event_placeOrderBtnActionPerformed

    private void remMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remMenuBtnActionPerformed
        // TODO add your handling code here:
        if(orderItemsList.getSelectedIndex()!=-1){
            currentOrderItems.remove(orderItemsList.getSelectedIndex());
            listModel1.remove(orderItemsList.getSelectedIndex());
        }
    }//GEN-LAST:event_remMenuBtnActionPerformed

    private void addMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuBtnActionPerformed
        // TODO add your handling code here:
        if(menuTable.getSelectedRow()!=-1 && !listModel1.contains((String)menuTable.getValueAt(menuTable.getSelectedRow(),0)) && MenuQtyTxt.getText().length()!=0){
            String name=(String)menuTable.getValueAt(menuTable.getSelectedRow(), 0);
            currentOrderItems.add(menuDb.FindInMenuByName(name,Integer.parseInt(MenuQtyTxt.getText())));
            listModel1.addElement(name);
        }
    }//GEN-LAST:event_addMenuBtnActionPerformed

    private void orderRefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderRefreshBtnActionPerformed
        // TODO add your handling code here:
        initOrdersListModel();
    }//GEN-LAST:event_orderRefreshBtnActionPerformed

    private void remOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remOrderBtnActionPerformed
        // TODO add your handling code here:
        if(ordersList.getSelectedIndex()!=-1){
            ordersDb.removeOrder(orders.get(ordersList.getSelectedIndex()).getId());
            orders.remove(ordersList.getSelectedIndex());
            listModel2.remove(ordersList.getSelectedIndex());
        }
    }//GEN-LAST:event_remOrderBtnActionPerformed

    private void showDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDetailsBtnActionPerformed
        // TODO add your handling code here:
        if(ordersList.getSelectedIndex()!=-1){
            initDetailsTableModel();
            Order order=orders.get(ordersList.getSelectedIndex());
            for(MenuItem item: (ArrayList<MenuItem>)order.getItems()){
                String row[]={item.getName(),String.valueOf(item.getPrice()),String.valueOf(item.getQty())};
                tableModel2.addRow(row);
            }
            totalLabel.setText("Total: Rs."+String.format("%5.2f", order.getTotal()));
        }
    }//GEN-LAST:event_showDetailsBtnActionPerformed

    private void appendOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendOrderBtnActionPerformed
        // TODO add your handling code here:
        if(ordersList.getSelectedIndex()!=-1){
            ordersDb.appendOrder(orders.get(ordersList.getSelectedIndex()).getId(), currentOrderItems);
            listModel1.clear();
            MenuQtyTxt.setText("");
            currentOrderItems.clear();
            initOrdersListModel();
        }
    }//GEN-LAST:event_appendOrderBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MenuQtyTxt;
    private javax.swing.JButton addMenuBtn;
    private javax.swing.JButton appendOrderBtn;
    private javax.swing.JTable detailsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable menuTable;
    private javax.swing.JList<String> orderItemsList;
    private javax.swing.JButton orderRefreshBtn;
    private javax.swing.JList<String> ordersList;
    private javax.swing.JButton placeOrderBtn;
    private javax.swing.JButton remMenuBtn;
    private javax.swing.JButton remOrderBtn;
    private javax.swing.JButton showDetailsBtn;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

    private void setResizaable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
