/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rms.screens;

import javax.swing.*;
import java.awt.*;
import rms.resources.staffDbHandler;

/**
 *
 * @author rammy
 */
public class regStaff extends javax.swing.JFrame {
    private staffDbHandler staffDb;
    private JFrame f;
    /**
     * Creates new form regStaff
     */
    public regStaff() {
        staffDb=new staffDbHandler();
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setTitle("RMS Register");
        setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        ageLabel = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        ageSeparator = new javax.swing.JSeparator();
        signupBtn = new javax.swing.JButton();
        salaryLabel = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        salarySeparator = new javax.swing.JSeparator();
        passwordLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 228, 183));
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 120, -1));

        username.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        username.setForeground(new java.awt.Color(204, 204, 204));
        username.setBorder(null);
        username.setOpaque(false);
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 260, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 260, 10));

        password.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setBorder(null);
        password.setOpaque(false);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 260, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 260, 20));

        ageLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(249, 228, 183));
        ageLabel.setText("Age");
        jPanel1.add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 120, -1));

        age.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        age.setForeground(new java.awt.Color(204, 204, 204));
        age.setBorder(null);
        age.setOpaque(false);
        age.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ageMouseClicked(evt);
            }
        });
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 260, -1));
        jPanel1.add(ageSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 218, 260, -1));

        signupBtn.setBackground(new java.awt.Color(223, 201, 153));
        signupBtn.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(91, 79, 71));
        signupBtn.setText("SIGN UP");
        signupBtn.setBorder(null);
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });
        jPanel1.add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 240, 40));

        salaryLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(249, 228, 183));
        salaryLabel.setText("Salary");
        jPanel1.add(salaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 120, -1));

        salary.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        salary.setForeground(new java.awt.Color(204, 204, 204));
        salary.setBorder(null);
        salary.setOpaque(false);
        salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salaryMouseClicked(evt);
            }
        });
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        jPanel1.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 260, -1));
        jPanel1.add(salarySeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 260, 20));

        passwordLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(249, 228, 183));
        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 120, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 201, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 340, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/screens/login2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 340, 440));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/screens/login3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 340, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 916, 446));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
        username.setText("");
    }//GEN-LAST:event_usernameMouseClicked

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        boolean rest=username.getText().equals("")||String.valueOf(password.getPassword()).equals("")||age.getText().equals("")||salary.getText().equals("");
        if(!rest){

            String uname=username.getText();
            String pass=String.valueOf(password.getPassword());
            int a=Integer.parseInt(age.getText());
            double b=Double.parseDouble(salary.getText());
            age.setText("");
            salary.setText("");
            username.setText("");
            //System.out.println("Works till here");
        
            boolean res=staffDb.registerStaff(uname, pass, a, b);
            if(res){
                this.dispose();
                loginStaff_screen app1=new loginStaff_screen();
                app1.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(f,"Invalid Username or password");
//                    System.out.println("Registration failed!");
        }
        else
                JOptionPane.showMessageDialog(f,"Enter Valid details.");
    }//GEN-LAST:event_signupBtnActionPerformed

    private void ageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ageMouseClicked
        // TODO add your handling code here:
        age.setText("");
    }//GEN-LAST:event_ageMouseClicked

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void salaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryMouseClicked
        // TODO add your handling code here:
        salary.setText("");
    }//GEN-LAST:event_salaryMouseClicked

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JSeparator ageSeparator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField salary;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JSeparator salarySeparator;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
