/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rat.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import rar.resources.MenuDbHandler;
import rar.resources.OrderDbHandler;
import rat.models.MenuItem;
import rat.models.Order;
import rat.models.Utils;
import java.lang.String;
import java.text.SimpleDateFormat;
import java.util.Date;
import rat.StringConstants;

/**
 *
 * @author Rishabh
 */
public class MyApp extends javax.swing.JFrame {

    /**
     * Creates new form MyApp
     */
    
    private DefaultTableModel tableModel1, tableModel2;
    private DefaultListModel listModel1, listModel2;
    private MenuDbHandler menuDb;
    private OrderDbHandler orderDb;
    private ArrayList<MenuItem> currentOrderItems;
    private ArrayList<Order> orders;
    
    
    public MyApp() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setTitle("RMS app");
        setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        setResizable(false);
        
        currentOrderItems = new ArrayList();
        menuDb = new MenuDbHandler();
        orderDb = new OrderDbHandler();
        
        tableModel1 = new DefaultTableModel();
        listModel1 =new DefaultListModel();
        orderItemsList.setModel(listModel1);
                
        tableModel1.addColumn("Name");
        tableModel1.addColumn("Price");
        
        menuTable.setModel(tableModel1);
        
        ArrayList<MenuItem> items = menuDb.getMenu();
        
        for(MenuItem item : items){
            
            tableModel1.addRow(new String[]{item.getName(), String.valueOf(item.getPrice())});
        }
        
        initListModel1();
        initTableModel1();
    }
    
    private void initListModel1(){
        listModel2 = new DefaultListModel();
        
        orders = Utils.arrangeOrder(orderDb.getOrder());
        System.out.println(orders);
        
        for(Order order : orders){
            
            listModel2.addElement("Order " + order.getOrderNo());
            
        }
        
        ordersList.setModel(listModel2);
        
        
    }
    
    private void initTableModel1(){
        tableModel2 = new DefaultTableModel();
        detailsTable.setModel(tableModel2);
        tableModel2.addColumn("NAME");
        tableModel2.addColumn("PRICE");
        tableModel2.addColumn("QTY");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderItemsList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        qtyField = new javax.swing.JTextField();
        addMenuItemsBtn = new javax.swing.JButton();
        removeMenuItemsBtn = new javax.swing.JButton();
        placeOrderBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ordersList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        totalLabel = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        removeOrderBtn = new javax.swing.JButton();
        showDetailsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rate-A-Touille");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU");

        jScrollPane1.setViewportView(menuTable);

        jScrollPane2.setViewportView(orderItemsList);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("QTY:");

        qtyField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qtyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyFieldActionPerformed(evt);
            }
        });

        addMenuItemsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addMenuItemsBtn.setText("Add");
        addMenuItemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuItemsBtnActionPerformed(evt);
            }
        });

        removeMenuItemsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeMenuItemsBtn.setText("Remove");
        removeMenuItemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMenuItemsBtnActionPerformed(evt);
            }
        });

        placeOrderBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        placeOrderBtn.setText("Place order");
        placeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ORDERS");

        jScrollPane3.setViewportView(ordersList);

        jScrollPane4.setViewportView(detailsTable);

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalLabel.setText("TOTAL:");

        refreshBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        removeOrderBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeOrderBtn.setText("Remove");
        removeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeOrderBtnActionPerformed(evt);
            }
        });

        showDetailsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showDetailsBtn.setText("Show Details");
        showDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(addMenuItemsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeMenuItemsBtn)
                        .addGap(2, 2, 2)
                        .addComponent(placeOrderBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showDetailsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeOrderBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addMenuItemsBtn)
                        .addComponent(qtyField)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeOrderBtn)
                            .addComponent(removeMenuItemsBtn))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(removeOrderBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showDetailsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qtyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_qtyFieldActionPerformed

    private void placeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBtnActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        String date = df.format(new Date());
        String orderItem = "";
        
        for(MenuItem item : currentOrderItems){
        
            orderItem += item.getId() + ":" + item.getQty() + ",";
        }
        orderItem = orderItem.substring(0,orderItem.length()-1);
        orderDb.addOrder2(date, orderItem);
        
        listModel1.clear();
        qtyField.setText("");
    }//GEN-LAST:event_placeOrderBtnActionPerformed

    private void removeMenuItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMenuItemsBtnActionPerformed
        // TODO add your handling code here:
        if(orderItemsList.getSelectedIndex() != -1){
            
            currentOrderItems.remove(orderItemsList.getSelectedIndex());
            listModel1.remove(orderItemsList.getSelectedIndex());
        }
    }//GEN-LAST:event_removeMenuItemsBtnActionPerformed

    private void addMenuItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuItemsBtnActionPerformed
        // TODO add your handling code here:
        if(menuTable.getSelectedRow() != -1 && !listModel1.contains((String) menuTable.getValueAt(menuTable.getSelectedRow(),0)) && qtyField.getText().length() != 0){
            
            String name = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 0);
            currentOrderItems.add(menuDb.getMenuItem(name,Integer.parseInt(qtyField.getText())));
            listModel1.addElement(name);
        }
    }//GEN-LAST:event_addMenuItemsBtnActionPerformed

    private void showDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDetailsBtnActionPerformed
        // TODO add your handling code here:
        if(ordersList.getSelectedIndex() != -1){
            
            initTableModel1();
            
            
            Order order = orders.get(ordersList.getSelectedIndex());
            order.DisplayDetails();
            
            for(MenuItem item : (ArrayList<MenuItem>)order.getItems()){
                String row[] = {item.getName(),String.valueOf(item.getPrice()),String.valueOf(item.getQty())};
                System.out.println(row);
                tableModel2.addRow(row);
            }
            
            totalLabel.setText("Total: Rs." + String.format("%5.2f", order.getTotal()));
        }
    }//GEN-LAST:event_showDetailsBtnActionPerformed

    private void removeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeOrderBtnActionPerformed
        // TODO add your handling code here:
        if(ordersList.getSelectedIndex() != -1){
            
            orderDb.removeOrder(orders.get(ordersList.getSelectedIndex()).getOrderNo());
            orders.remove(ordersList.getSelectedIndex());
            listModel2.remove(ordersList.getSelectedIndex());
        }
    }//GEN-LAST:event_removeOrderBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        initListModel1();
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMenuItemsBtn;
    private javax.swing.JTable detailsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable menuTable;
    private javax.swing.JList<String> orderItemsList;
    private javax.swing.JList<String> ordersList;
    private javax.swing.JButton placeOrderBtn;
    private javax.swing.JTextField qtyField;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton removeMenuItemsBtn;
    private javax.swing.JButton removeOrderBtn;
    private javax.swing.JButton showDetailsBtn;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
