/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tdocratatouille.screens;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import tdocratatouille.models.MenuItem;
import tdocratatouille.models.Order;
import tdocratatouille.resources.MenuDBHandler;
import tdocratatouille.resources.OrdersDBHandler;
import tdocratatouille.resources.Utils;

/**
 *
 * @author Divyo
 */
public class AppScreen extends javax.swing.JFrame {
    
    private DefaultTableModel tableModel1,tableModel2;
    private DefaultListModel listModel1,listModel2;
    private MenuDBHandler menuDb;
    private OrdersDBHandler ordersDb;
    private ArrayList<MenuItem> currentOrderItems;
    private ArrayList<Order> orders;
    private String timeStamp="";
    private int oldId=-1;

    /**
     * Creates new form AppScreen
     */
    public AppScreen() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setTitle("Menu and Orders");
        setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        setResizable(false);
        
        currentOrderItems = new ArrayList();
        menuDb = new MenuDBHandler();
        ordersDb = new OrdersDBHandler();
        
        tableModel1 = new DefaultTableModel();
        listModel1 = new DefaultListModel();
        OrderItemsList.setModel(listModel1);
        
        tableModel1.addColumn("NAME");
        tableModel1.addColumn("PRICE");
        
        MenuTable.setModel(tableModel1);
        
        ArrayList<MenuItem> items = menuDb.getMenu();
        
        for(MenuItem item : items){
            tableModel1.addRow(new String[]{item.getName(),String.valueOf(item.getPrice())});
        }
        
        initOrdersListModel();
        initDetailsTableModel();
       
    }
    
    private void initOrdersListModel(){
        listModel2 = new DefaultListModel();
        orders = Utils.arrangeOrders(ordersDb.getOrders());
        
        for(Order order : orders){
            listModel2.addElement("Order "+order.getId());
            
        }
        
        OrdersList.setModel(listModel2);
  
    }
    
    private void initDetailsTableModel(){
        tableModel2 = new DefaultTableModel();
        DetailsTable.setModel(tableModel2);
        tableModel2.addColumn("NAME");
        tableModel2.addColumn("PRICE");
        tableModel2.addColumn("QTY");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        MenuTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderItemsList = new javax.swing.JList<>();
        AddMenuItemBtn = new javax.swing.JButton();
        RemoveMenuItemBtn = new javax.swing.JButton();
        PlaceOrderBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        QtyField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OrdersList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        DetailsTable = new javax.swing.JTable();
        RefreshBtn = new javax.swing.JButton();
        RemoveOrderBtn = new javax.swing.JButton();
        ShowDetailsBtn = new javax.swing.JButton();
        TotalLabel = new javax.swing.JLabel();
        BackToMenuBtn = new javax.swing.JButton();
        AppendOrderBtn = new javax.swing.JButton();
        OrderNumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(33, 127, 44));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(238, 179, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        jLabel2.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rate-a-touille");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        MenuTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MenuTable.setOpaque(false);
        jScrollPane2.setViewportView(MenuTable);

        OrderItemsList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(OrderItemsList);

        AddMenuItemBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddMenuItemBtn.setText("Add");
        AddMenuItemBtn.setMargin(new java.awt.Insets(2, 8, 2, 8));
        AddMenuItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMenuItemBtnActionPerformed(evt);
            }
        });

        RemoveMenuItemBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RemoveMenuItemBtn.setText("Remove");
        RemoveMenuItemBtn.setMargin(new java.awt.Insets(2, 8, 2, 8));
        RemoveMenuItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMenuItemBtnActionPerformed(evt);
            }
        });

        PlaceOrderBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PlaceOrderBtn.setText("Place Order");
        PlaceOrderBtn.setMargin(new java.awt.Insets(2, 8, 2, 8));
        PlaceOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Qty :");

        QtyField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QtyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Orders");
        jLabel4.setOpaque(true);

        OrdersList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(OrdersList);

        DetailsTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(DetailsTable);

        RefreshBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RefreshBtn.setText("Refresh");
        RefreshBtn.setMargin(new java.awt.Insets(2, 8, 2, 8));
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });

        RemoveOrderBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RemoveOrderBtn.setText("Remove");
        RemoveOrderBtn.setMargin(new java.awt.Insets(2, 8, 2, 8));
        RemoveOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveOrderBtnActionPerformed(evt);
            }
        });

        ShowDetailsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ShowDetailsBtn.setText("Show Details");
        ShowDetailsBtn.setMargin(new java.awt.Insets(2, 8, 2, 8));
        ShowDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDetailsBtnActionPerformed(evt);
            }
        });

        TotalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalLabel.setText("Total :");

        BackToMenuBtn.setText("Back");
        BackToMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuBtnActionPerformed(evt);
            }
        });

        AppendOrderBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AppendOrderBtn.setText("+");
        AppendOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppendOrderBtnActionPerformed(evt);
            }
        });

        OrderNumLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OrderNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrderNumLabel.setText("Order No. ");
        OrderNumLabel.setOpaque(true);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddMenuItemBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RemoveMenuItemBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlaceOrderBtn))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(AppendOrderBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ShowDetailsBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RemoveOrderBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RefreshBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OrderNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 42, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BackToMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(BackToMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OrderNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(QtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PlaceOrderBtn)
                        .addComponent(RemoveMenuItemBtn)
                        .addComponent(AddMenuItemBtn)
                        .addComponent(RefreshBtn)
                        .addComponent(RemoveOrderBtn)
                        .addComponent(ShowDetailsBtn)
                        .addComponent(AppendOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TotalLabel)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QtyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_QtyFieldActionPerformed

    private void RemoveMenuItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveMenuItemBtnActionPerformed
        // TODO add your handling code here:
        if(OrderItemsList.getSelectedIndex() != -1){
            currentOrderItems.remove(OrderItemsList.getSelectedIndex());
            listModel1.remove(OrderItemsList.getSelectedIndex());
        }
    }//GEN-LAST:event_RemoveMenuItemBtnActionPerformed

    private void AddMenuItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMenuItemBtnActionPerformed
        // TODO add your handling code here:
        if(MenuTable.getSelectedRow() != -1 && !listModel1.contains((String)MenuTable.getValueAt(MenuTable.getSelectedRow(),0)) && QtyField.getText().length() != 0){
            
            String name = (String)MenuTable.getValueAt(MenuTable.getSelectedRow(),0);
            currentOrderItems.add(menuDb.FindInMenuByName(name,Integer.parseInt(QtyField.getText())));
            listModel1.addElement(name);//Try to add qty
        }
    }//GEN-LAST:event_AddMenuItemBtnActionPerformed

    private void RemoveOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveOrderBtnActionPerformed
        // TODO add your handling code here:
        
        if(OrdersList.getSelectedIndex() != -1){
            ordersDb.removeOrder(orders.get(OrdersList.getSelectedIndex()).getId());
            orders.remove(OrdersList.getSelectedIndex());
            listModel2.remove(OrdersList.getSelectedIndex());
            initDetailsTableModel();
            OrderNumLabel.setText("Order No.");
            
        }
    }//GEN-LAST:event_RemoveOrderBtnActionPerformed

    private void ShowDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDetailsBtnActionPerformed
        // TODO add your handling code here:
        
        if(OrdersList.getSelectedIndex() != -1){
            
            initDetailsTableModel();
            
            Order order = orders.get(OrdersList.getSelectedIndex());
            
            for(MenuItem item : (ArrayList<MenuItem>)order.getItems()){
                String row[] = {item.getName(),String.valueOf(item.getPrice()),String.valueOf(item.getQty())};
                tableModel2.addRow(row);
            }
            
            TotalLabel.setText("Total : $"+String.format("%5.2f",order.getTotal()));
            OrderNumLabel.setText("Order No. "+order.getId());
        }
    }//GEN-LAST:event_ShowDetailsBtnActionPerformed

    private void PlaceOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceOrderBtnActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        String date = df.format(new Date());
        if(timeStamp.equals(""))
            ordersDb.addOrder(date,currentOrderItems);
        else{
            
            ordersDb.appendOrder(oldId, currentOrderItems);
            oldId=-1;
            timeStamp="";
        }
        listModel1.clear();
        QtyField.setText("");
        currentOrderItems.clear();
    }//GEN-LAST:event_PlaceOrderBtnActionPerformed

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
        // TODO add your handling code here:
        initOrdersListModel();
        initDetailsTableModel();
        TotalLabel.setText("Total :");
        OrderNumLabel.setText("Order No.");
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void BackToMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuBtnActionPerformed
        // TODO add your handling code here:
        MenuScreen menu = new MenuScreen();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackToMenuBtnActionPerformed

    private void AppendOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppendOrderBtnActionPerformed
        // TODO add your handling code here:
        if(OrdersList.getSelectedIndex() != -1){
            Order order = orders.get(OrdersList.getSelectedIndex());
            
            listModel1.clear();
            OrderItemsList.setModel(listModel1);
            
            for(MenuItem item : (ArrayList<MenuItem>)order.getItems()){
                //currentOrderItems.add(item);
                listModel1.addElement(item.getName());
            }
            currentOrderItems.clear();//Clear current orders to prevent problems in appending
            timeStamp = order.getTimePlaced();
            oldId = order.getId();
            initDetailsTableModel();
            OrderNumLabel.setText("Order No.");
            
        }
    }//GEN-LAST:event_AppendOrderBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMenuItemBtn;
    private javax.swing.JButton AppendOrderBtn;
    private javax.swing.JButton BackToMenuBtn;
    private javax.swing.JTable DetailsTable;
    private javax.swing.JTable MenuTable;
    private javax.swing.JList<String> OrderItemsList;
    private javax.swing.JLabel OrderNumLabel;
    private javax.swing.JList<String> OrdersList;
    private javax.swing.JButton PlaceOrderBtn;
    private javax.swing.JTextField QtyField;
    private javax.swing.JButton RefreshBtn;
    private javax.swing.JButton RemoveMenuItemBtn;
    private javax.swing.JButton RemoveOrderBtn;
    private javax.swing.JButton ShowDetailsBtn;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
